[package]
name = "memory-layout"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.104", features = ["derive"], optional = true } # MIT/Apache-2.0

[features]
large_array_derive = []
serde = ["dep:serde"]
