cargo-features = ["edition2024"]
[package]
name = "aws-nitro-blobs"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[dependencies]

[build-dependencies]
data_downloader = "0.2"
hex-literal = "0.4.1"
