[package]
name = "enclave-runner"
version = "0.1.0-rc1"
authors = ["Jethro Beekman <jethro@fortanix.com>"]
license = "MPL-2.0"
description = """
High-level abstractions for running SGX enclaves.

This crate can be used to load and interface with SGX applications compiled for
the `x86_64-fortanix-unknown-sgx` target.
"""
repository = "https://github.com/fortanix/rust-sgx"
documentation = "https://docs.rs/enclave-runner/"
keywords = ["sgx", "enclave"]
categories = ["os", "hardware-support"]

[dependencies]
# Project dependencies
sgxs = { version = "0.6.0-rc1", path = "../sgxs", features = ["crypto-openssl"] }
fortanix-sgx-abi = { version = "0.1.0-rc1", path = "../fortanix-sgx-abi" }
sgx-isa = { version = "0.2.0-rc1", path = "../sgx-isa" }

# External dependencies
openssl = "0.10"         # Apache-2.0
failure = "0.1.1"        # MIT/Apache-2.0
failure_derive = "0.1.1" # MIT/Apache-2.0
fnv = "1"                # MIT/Apache-2.0
