[package]
name = "mem-correctness-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam = "0.8.0"
rand = "0.8.4"
num_cpus = "1.14.0"
sha2 = "0.10"

[package.metadata.fortanix-sgx]
# heap size (in bytes), the default heap size is 0x2000000.
heap-size=0x20000000
debug=false