[package]
name = "nsm"
version = "0.1.0"
authors = ["Raoul Strackx <raoul.strackx@fortanix.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nitro-attestation-verify = { path = "../nitro-attestation-verify" }
nsm-driver = { git = "https://github.com/aws/aws-nitro-enclaves-nsm-api", rev = "9ddb589875baf345d085a980aa96cf3a4e480ea8" }
nsm-io = { git = "https://github.com/aws/aws-nitro-enclaves-nsm-api", rev = "9ddb589875baf345d085a980aa96cf3a4e480ea8" }
serde_bytes = "0.11"
