[package]
name = "fortanix-vme-initramfs"
version = "0.1.0"
edition = "2024"

[dependencies]
cpio = "0.2"
derivative = "2.2.0"
flate2 = "1.0"
normalize-path = "0.2.1"
thiserror = "1.0"

[dev-dependencies]
hex-literal = "0.4"
sha2 = "0.9"
