[package]
name = "elf2uki"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "fortanix-vme-elf2uki"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.4", features = ["cargo", "derive"] }
confidential-vm-blobs = { path = "../confidential-vm-blobs/" }
env_logger = "0.9"
fortanix-vme-initramfs = { path = "../../fortanix-vme-initramfs" }
log = "0.4"
tempfile = "3"
