[package]
name = "elf2uki"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.54", features = ["cargo", "derive"] }
env_logger = "0.11.8"
fortanix-vme-initramfs = { path = "../../fortanix-vme-initramfs" }
log = "0.4.29"
tempfile = "3.24.0"
