[package]
name = "fortanix-vme-tools"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
aws-nitro-blobs = { path = "../aws-nitro-enclaves/aws-nitro-blobs" }
cargo_toml = "0.22.0"
clap = { version = "4.0", features = ["derive"] }
fortanix-vme-eif = { path = "../fortanix-vme-eif" }
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
