[package]
name = "blobs-tool"
version = "0.1.0"
edition = "2024"
description = "This is a tool to download Nitro enclave related files. This tool downloads all necessary files from aws's nitro-cli repository."

[dependencies]
anyhow = "1.0"
clap = { version = "4.5.51", features = ["cargo"] }
env_logger = "0.9"
futures-util = "0.3.28"
hex = "0.4.3"
log = "0.4.28"
reqwest = { version = "0.12", features = ["blocking", "stream"] }
sha2 = "0.10.9"
