[package]
name = "fortanix-vme-runner"
version = "0.1.0"
edition = "2018"
authors = ["Fortanix, Inc."]

[dependencies]
# Workspace dependencies
confidential-vm-blobs = { path = "../tools/confidential-vm-blobs/" }
enclave-runner = { version = "0.8.0", path = "../../enclave-runner" }
fortanix-vme-abi = { path = "../fortanix-vme-abi", features = ["std"] }
fortanix-vme-eif = { path = "../fortanix-vme-eif" }
# External dependencies
anyhow = "1.0"
b64-ct = "0.1.3"
clap = { version = "4.0", features = ["derive"] }
clap-verbosity-flag = "3.0.3"
env_logger = "0.9.0"
fnv = "1.0.7"
futures = "0.3"
log = "0.4.21"
nitro-cli = { git = "https://github.com/aws/aws-nitro-enclaves-cli.git", rev = "v1.4.2" }
nix = { version = "0.30.0", features = ["fs", "ioctl", "socket"] }
rand = "0.7.3"
serde_cbor = { version = "0.11" }
sev = { version = "7.1.0", features = [
    "snp",
    "openssl",
] } # Unfortunately, we need the `openssl` feature - https://github.com/virtee/sev/issues/387
thiserror = "1.0"
tokio = { version = "1.35", features = ["full"] } # MIT
tokio-vsock = { version = "0.7.2" }
vsock = "0.5"
