[package]
name = "fortanix-vme-runner"
version = "0.1.0"
edition = "2018"
authors = ["Fortanix, Inc."]

[dependencies]
env_logger = "0.8.4"
fnv = "1.0.7"
fortanix-vme-abi = { path = "../fortanix-vme-abi", features = ["std"] }
log = "0.4.21"
nix = "0.22.1"
serde = { version = "1.0", features = ["derive"] }
serde_cbor = { version = "0.11" }
vsock = "0.2.4"
