[package]
name = "fortanix-vme-runner"
version = "0.1.0"
edition = "2018"
authors = ["Fortanix, Inc."]

[dependencies]
clap = { version = "4.0", features = ["derive"] }
env_logger = "0.11.8"
fnv = "1.0.7"
fortanix-vme-abi = { path = "../fortanix-vme-abi", features = ["std"] }
fortanix-vme-eif = { path = "../fortanix-vme-eif" }
log = "0.4.21"
nitro-cli = { git = "https://github.com/aws/aws-nitro-enclaves-cli.git", rev = "v1.4.2" }
nix = "0.22.1"
rand = "0.7.3"
serde = { version = "1.0", features = ["derive"] }
serde_cbor = { version = "0.11" }
vsock = "0.2.4"
