[package]
name = "ftxvme-runner"
version = "0.1.0"
edition = "2018"
authors = ["Fortanix, Inc."]

[dependencies]
clap = { version = "4.0", features = ["derive"] }
env_logger = "0.8.4"
fnv = "1.0.7"
fortanix-vme-abi = { path = "../fortanix-vme-abi", features = ["std"] }
libc = { version = "0.2", features = ["extra_traits"] }
log = "0.4.14"
nitro-cli = "1.1.0"
nix = "0.22.1"
serde = { version = "1.0", features = ["derive"] }
serde_cbor = { version = "0.11" }
vsock = "0.2.4"
