[package]
name = "eif-tools"
version = "0.1.0"
authors = ["Fortanix, Inc."]
license = "MPL-2.0"
edition = "2018"
description = """
Utilities for working with the AWS Nitro Encalve Image File format.
"""
repository = "https://github.com/fortanix/rust-sgx"
documentation = "https://edp.fortanix.com/docs/"
homepage = "https://edp.fortanix.com/"
keywords = ["nitro-enclaves", "enclave", "eif"]
categories = ["command-line-utilities"]

[dependencies]
clap = "2.34"
elf = "0.0.10"
env_logger = "0.11"
log = "0.4"
nitro-cli = { git = "https://github.com/aws/aws-nitro-enclaves-cli.git", rev = "v1.4.2" }
