[package]
name = "tdx-ql"
version = "0.1.0"
edition = "2021"
readme = "README.md"

[dependencies]
sgx-isa = { version = "0.5.0", path = "../../intel-sgx/sgx-isa" }
nix = { version = "0.30", features = ["ioctl"] }

[dev-dependencies]
clap = { version = "4", features = ["derive"] }

[features]
large_array_derive = ["sgx-isa/large_array_derive"]
