[package]
# Unfortunately crates.io prevents us from changing the name to `sgx-pkix`
name = "sgx_pkix"
version = "0.2.0"
authors = ["Fortanix, Inc."]
edition = "2018"
license = "MPL-2.0"
repository = "https://github.com/fortanix/rust-sgx"
description = "TLS Certificate encoding and decoding helpers for the SGX environment."
keywords = [ "certificate-handling", "sgx" ]
categories = ["cryptography"]

[dependencies]
byteorder = "1.0"
pkix = "0.1.1"
sgx-isa = { version = "0.4", path = "../sgx-isa" }
quick-error = "1.1.0"
lazy_static = "1"
